

INSERT INTO CLIENTES (nome, email) VALUES ('vitor', 'vitor@senac');
INSERT INTO CLIENTES (nome, email) VALUES ('gabriel', 'gabriel@senac');
INSERT INTO CLIENTES (nome, email) VALUES ('luis', 'luis@senac');
SELECT nome,email FROM CLIENTES;


INSERT  INTO PRODUTOS (nome, preco, tipo) VALUES ('Notebook X', 3000, 'Notebook');
INSERT  INTO PRODUTOS (nome, preco, tipo) VALUES ('Notebook Y', 3500, 'Notebook');
INSERT INTO PRODUTOS (nome, preco, tipo) VALUES ('Celular Z', 2000, 'Celular');
SELECT nome, preco, tipo FROM PRODUTOS;

UPDATE PRODUTOS SET preco = preco * 1.10 WHERE tipo = 'Notebook';

-- CREATE
DROP TABLE PEDIDOS PURGE;
CREATE TABLE PEDIDOS (
  id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  cliente_id NUMBER NOT NULL,
  produto_id NUMBER NOT NULL,
  status     VARCHAR2(20) NOT NULL CHECK (status IN ('ABERTO','FINALIZADO','CANCELADO'))
);



INSERT   INTO PEDIDOS (cliente_id, produto_id, status) VALUES (1, 1, 'ABERTO');
INSERT   INTO PEDIDOS (cliente_id, produto_id, status) VALUES (2, 2, 'CANCELADO');
INSERT   INTO PEDIDOS (cliente_id, produto_id, status) VALUES (3, 3, 'FINALIZADO');

SELECT cliente_id, produto_id, status FROM PEDIDOS;

DELETE FROM PEDIDOS WHERE STATUS = 'CANCELADO';


DROP TABLE CLIENTES_STG PURGE;
CREATE TABLE CLIENTES_STG (
  nome  VARCHAR2(100) NOT NULL,
  email VARCHAR2(120) NOT NULL
);



INSERT INTO CLIENTES_STG (nome, email) VALUES ('vitor', 'vitor@Lindo.com');
INSERT INTO CLIENTES_STG (nome, email) VALUES ('Daniela Nov', 'daniela@techplus.com');
SELECT nome, email FROM CLIENTES_STG;

DELETE FROM CLIENTES_STG WHERE nome = 'Daniela Nova';
DELETE FROM CLIENTES_STG WHERE nome = 'vitor';
DELETE FROM CLIENTES_STG WHERE email = 'ana@techplus.com';



MERGE INTO CLIENTES c
USING CLIENTES_STG s
ON (c.email = s.email)
WHEN MATCHED THEN
  UPDATE SET c.nome = s.nome
WHEN NOT MATCHED THEN
  INSERT (nome, email) VALUES (s.nome, s.email);