--EXERCICIO 1
SELECT PRODUTO, VALOR
FROM VENDAS
WHERE VALOR > (SELECT MIN (VALOR) FROM VENDAS WHERE CATEGORIA = 'Eletrônicos');

--EXERCICIO 2
SELECT vendedor, produto, valor
FROM VENDAS 
WHERE valor =(SELECT MAX(VALOR) FROM VENDAS);
-- EXERCICIO 3
SELECT DISTINCT CATEGORIA
FROM VENDAS v
WHERE VALOR > (SELECT AVG(VALOR)FROM VENDAS);
-- EXERCICIO 4
SELECT *
FROM (
    SELECT
    vendedor,
    produto,
    valor,
        ROW_NUMBER() OVER (PARTITION BY vendedor ORDER BY valor DESC) AS ranking
    FROM VENDAS) 
WHERE ranking <= 3;